### ISSUE TITLE
Electric Motors and ESC

### ISSUE THREAD

**Issue by satyamrocksu** [rajatsharma369007/Electric-skateboard#2]
Hey Rajat , 

I was going through your Electric Skateboard . I was planning to build one so i wanted to know from where u got  ESC and Electric Motor. I did lot of research but didn't found ESC and Motors in India. 

So please can u guide me from where can i get.
its will be really helpful.

**Comment by rajatsharma369007** [comment]
Hi @satyamrocksu 

yes, that is difficult 
there are some Indian sites (RcBazaar) that sometimes have these kinds of ESC and Motors but it is rare. I myself purchased from the Chinese site "Everbuying.net" but this site is closed now
you can have a look on Alibaba, Gearbest, or Banggood. But due to the Covid19 pandemic, it is difficult for you to get it soon.

Thanks
